# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MARTHAui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MARTHA_UI(object):
    def setupUi(self, MARTHA_UI):
        MARTHA_UI.setObjectName("MARTHA_UI")
        MARTHA_UI.resize(1366, 720)
        MARTHA_UI.setStyleSheet("background color: black")
        self.centralwidget = QtWidgets.QWidget(MARTHA_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.BG1 = QtWidgets.QLabel(self.centralwidget)
        self.BG1.setGeometry(QtCore.QRect(-24, -28, 1561, 811))
        self.BG1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.BG1.setText("")
        self.BG1.setObjectName("BG1")
        self.BG2 = QtWidgets.QLabel(self.centralwidget)
        self.BG2.setGeometry(QtCore.QRect(10, 10, 471, 491))
        self.BG2.setStyleSheet("background-color: rgb(0, 12, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.BG2.setText("")
        self.BG2.setObjectName("BG2")
        self.BG2_2 = QtWidgets.QLabel(self.centralwidget)
        self.BG2_2.setGeometry(QtCore.QRect(680, 300, 661, 271))
        self.BG2_2.setStyleSheet("background-color: rgb(0, 12, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.BG2_2.setText("")
        self.BG2_2.setObjectName("BG2_2")
        self.GIF1 = QtWidgets.QLabel(self.centralwidget)
        self.GIF1.setGeometry(QtCore.QRect(20, 20, 461, 471))
        self.GIF1.setText("")
        self.GIF1.setPixmap(QtGui.QPixmap("MARTHA GUI MATERIALS/faceman.gif"))
        self.GIF1.setObjectName("GIF1")
        self.GIF3 = QtWidgets.QLabel(self.centralwidget)
        self.GIF3.setGeometry(QtCore.QRect(-40, 540, 201, 151))
        self.GIF3.setText("")
        self.GIF3.setPixmap(QtGui.QPixmap("MARTHA GUI MATERIALS/spheres-motion-for-ai-product-design-by-gleb-large.gif"))
        self.GIF3.setObjectName("GIF3")
        self.BG2_3 = QtWidgets.QLabel(self.centralwidget)
        self.BG2_3.setGeometry(QtCore.QRect(1020, 10, 321, 281))
        self.BG2_3.setStyleSheet("background-color: rgb(0, 12, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.BG2_3.setText("")
        self.BG2_3.setObjectName("BG2_3")
        self.GIF4 = QtWidgets.QLabel(self.centralwidget)
        self.GIF4.setGeometry(QtCore.QRect(1030, 20, 301, 261))
        self.GIF4.setText("")
        self.GIF4.setPixmap(QtGui.QPixmap("MARTHA GUI MATERIALS/9e759fd37ccd98da121b670249f34afa.gif"))
        self.GIF4.setObjectName("GIF4")
        self.GIF5 = QtWidgets.QLabel(self.centralwidget)
        self.GIF5.setGeometry(QtCore.QRect(530, 20, 401, 91))
        self.GIF5.setText("")
        self.GIF5.setPixmap(QtGui.QPixmap("MARTHA GUI MATERIALS/T8bahf.gif"))
        self.GIF5.setObjectName("GIF5")
        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(730, 650, 251, 61))
        self.text_time.setStyleSheet("background-color: Transparent;")
        self.text_time.setObjectName("text_time")
        self.text_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_date.setGeometry(QtCore.QRect(730, 580, 251, 61))
        self.text_date.setStyleSheet("background-color: Transparent;")
        self.text_date.setObjectName("text_date")
        self.text_temperature = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_temperature.setGeometry(QtCore.QRect(470, 580, 251, 61))
        self.text_temperature.setStyleSheet("background-color: Transparent;")
        self.text_temperature.setObjectName("text_temperature")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(210, 520, 231, 71))
        self.start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: none;\n"
"color: rgb(0, 170, 255);\n"
"font: 30pt \"Courier New\";")
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 510, 251, 171))
        self.label.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(210, 600, 231, 71))
        self.exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: none;\n"
"color: rgb(0, 170, 255);\n"
"font: 30pt \"Courier New\";")
        self.exit.setObjectName("exit")
        self.text_day = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_day.setGeometry(QtCore.QRect(990, 580, 251, 61))
        self.text_day.setStyleSheet("background-color: Transparent;")
        self.text_day.setObjectName("text_day")
        self.GIF6_2 = QtWidgets.QLabel(self.centralwidget)
        self.GIF6_2.setGeometry(QtCore.QRect(690, 310, 641, 251))
        self.GIF6_2.setText("")
        self.GIF6_2.setPixmap(QtGui.QPixmap("GUI For MARTHA/B.G_Template_1.gif"))
        self.GIF6_2.setObjectName("GIF6_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(590, 110, 311, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("GUI For MARTHA/Earth_Template.gif"))
        self.label_2.setObjectName("label_2")
        self.BG1.raise_()
        self.BG2.raise_()
        self.BG2_2.raise_()
        self.GIF1.raise_()
        self.GIF3.raise_()
        self.BG2_3.raise_()
        self.GIF4.raise_()
        self.GIF5.raise_()
        self.text_time.raise_()
        self.text_date.raise_()
        self.text_temperature.raise_()
        self.label.raise_()
        self.start.raise_()
        self.exit.raise_()
        self.text_day.raise_()
        self.GIF6_2.raise_()
        self.label_2.raise_()
        MARTHA_UI.setCentralWidget(self.centralwidget)

        self.retranslateUi(MARTHA_UI)
        QtCore.QMetaObject.connectSlotsByName(MARTHA_UI)

    def retranslateUi(self, MARTHA_UI):
        _translate = QtCore.QCoreApplication.translate
        MARTHA_UI.setWindowTitle(_translate("MARTHA_UI", "MainWindow"))
        self.start.setText(_translate("MARTHA_UI", "START"))
        self.exit.setText(_translate("MARTHA_UI", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MARTHA_UI = QtWidgets.QMainWindow()
    ui = Ui_MARTHA_UI()
    ui.setupUi(MARTHA_UI)
    MARTHA_UI.show()
    sys.exit(app.exec_())
